# Generated by Django 6.1.2 on 2026-10-08 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='INN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, unique=True, verbose_name='Название (рус.)')),
                ('name_lat', models.CharField(blank=True, max_length=200, verbose_name='Название (лат.)')),
                ('atc_code', models.CharField(blank=True, max_length=20, verbose_name='ATC-код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'МНН',
                'verbose_name_plural': 'МНН (справочник)',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('is_24h', models.BooleanField(default=False, verbose_name='Круглосуточная')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Аптека',
                'verbose_name_plural': 'Аптеки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Торговое название')),
                ('form', models.CharField(choices=[('tablets', 'Таблетки'), ('capsules', 'Капсулы'), ('solution', 'Раствор'), ('ointment', 'Мазь'), ('spray', 'Спрей'), ('other', 'Другое')], default='tablets', max_length=20, verbose_name='Форма выпуска')),
                ('dosage', models.CharField(blank=True, max_length=100, verbose_name='Дозировка')),
                ('is_prescription', models.BooleanField(default=False, verbose_name='По рецепту')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('inn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='main.inn', verbose_name='МНН')),
            ],
            options={
                'verbose_name': 'Лекарство',
                'verbose_name_plural': 'Лекарства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('resident', 'Житель'), ('pharmacist', 'Фармацевт'), ('admin', 'Администратор')], default='resident', max_length=20, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacists', to='main.pharmacy', verbose_name='Аптека (для фармацевта)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена, ₽')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='main.medicine', verbose_name='Лекарство')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='main.pharmacy', verbose_name='Аптека')),
            ],
            options={
                'verbose_name': 'Наличие',
                'verbose_name_plural': 'Наличие',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('rejected', 'Отклонена'), ('done', 'Выдана'), ('cancelled', 'Отменена пользователем')], default='new', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main.stock', verbose_name='Наличие')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['name'], name='main_medici_name_84c56e_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['inn'], name='main_medici_inn_id_435b6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('pharmacy', 'medicine')},
        ),
    ]
